Basic:
  BlogDir: "../tmp/content"
  ImageDir: "../tmp/content/assert"
  TemplateFile: "/"
  OutputDir: "../tmp/imageOut"
  HttpBasePath: "https://github.com/"

LogStrategy:
  LogToFile: false
  LogFile: "/"
