Basic:
  BlogDir: "../tmp/content"
  ImageDir: "../tmp/content/assert"
  TemplateFile: "/"
  OutputDir: "../tmp/imageOut"
  HttpBasePath: "https://raw.githubusercontent.com/roaraeonliou/roaraeonliou.github.io/main/"
  DateLayout: "2006-01-02 15:04:05"

LogStrategy:
  LogToFile: false
  LogFile: "/"

FileMeta:
  Author: "RLTEA"

DataBase:
  DBFile: "../tmp/meta.db"


