Basic:
  BlogDir: "../content"
  ImageDir: "../content/assert"
  TemplateFile: "/"
  OutputDir: "../static"
  HttpBasePath: "https://raw.githubusercontent.com/roaraeonliou/roaraeonliou.github.io/static/"
  DateLayout: "2006-01-02"
#  DateLayout: "2006-01-02 15:04:05"

LogStrategy:
  LogToFile: false
  LogFile: "/"

FileMeta:
  Author: "RLTEA"

DataBase:
  DBFile: "../meta.db"

SearchPageConfig:
  Require: true
  Title: "Search"
  Layout: "search"
  Summary: "search"
  Placeholder: "search..."


ArchivesPageConfig:
  Require: true
  Title: "Archives"
  Layout: "archives"
  Url: "/archives/"
  Summary: "archives"



